/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:b84ec349-a305-4642-8056-e7634f01c57c",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_OyrOKwoj6",
    "aws_user_pools_web_client_id": "7189qd6m2labohr54vblsagqes",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "equifoodareactnativeed05037074bd4f8e820234c41bf224922-dev",
    "aws_user_files_s3_bucket_region": "ca-central-1"
};


export default awsmobile;
