CREATE TABLE admin (
 id INT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(50) NULL DEFAULT NULL,
  last_name VARCHAR(50) NULL DEFAULT NULL,
  email VARCHAR(50) NULL DEFAULT NULL,
  passwordHash VARCHAR(32) NOT NULL,
  PRIMARY KEY(id)
);

